### ISSUE TITLE
how to run fuzzer

### ISSUE THREAD

**Issue by baptistapedro** [andreafioraldi/frida-fuzzer#14]
in the docs, there's the line to compile the fuzzer `tst_ndk_x64.js`
`host$ frida-compile -x tests/test_ndk_x64.js -o fuzzer-agent.js`   it outputs a fuzzer-agent.js

and then to run it

`host$ ./frida-fuzzer -U -o output_folder/ com.example.ndktest1`

we've compiled the .js file and generated the fuzzer-agent.js but when we run ./frida-fuzzer how does it know what is the right harness to run with frida-fuzzer if the `fuzzer-agent` was never passed in the command line?

**Comment by andreafioraldi** [comment]
grep "fuzzer-agent.js" ./frida-fuzzer
