### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by symeonp** [andreafioraldi/frida-fuzzer#3]
Heyia (posting on the right project!)

Been trying to run the demo linux one, however am getting:

```
python3 ../frida-fuzzer -script test_linux_x64.js -spawn ./test_linux64
 >> Temporary output folder : /tmp/frida_fuzz_out_fq7ezsj1
{'type': 'error', 'description': 'ReferenceError: require is not defined', 'stack': 'ReferenceError: require is not defined\n    at /script1.js:1:12', 'fileName': '/script1.js', 'lineNumber': 1, 'columnNumber': 12}
 ************** FUZZER ERROR! **************
  line 1: ReferenceError: require is not defined
  JS stacktrace:

ReferenceError: require is not defined
    at /script1.js:1:12

 >> Press Control-C to exit...
script is destroyed
^C
```

I added an extra print statement to see the whole message. Not sure where this script1.js
comes from, but include("./fuzz") has an index.js which includes all the modules.
Am I missing something here? Latest frida version, 12.8.0!

**Comment by andreafioraldi** [comment]
Read the README please. You have to compile the harness with frida-compile.
`frida-compile -x tests/test_linux_x64.js -o fuzzer-agent.js`

**Comment by symeonp** [comment]
Ah, thanks, didn't realise there's a frida-compile tool, sorry!
