### ISSUE TITLE
Fork server not enabled

### ISSUE THREAD

**Issue by JoeyJiao** [andreafioraldi/frida-fuzzer#9]
Trying to spawn the fuzzer, but found that target process pid keeps the same.
Check the code, forkserver is not developed. WIP?

**Comment by andreafioraldi** [comment]
Fork server is not in the scope. fork can't work with multithreaded apps, that are the scope of an injectable fuzzer. Anyway, frida-fuzzer aim is to work also on Windows, where forkserver is not an option.
